### ISSUE TITLE
[프론트엔드] 회원가입 페이지 (예시, 애런)

### ISSUE THREAD

**Issue by aaronryu** [ASAC-marketplace/frontend#1]
## ISSUE
회원가입 페이지 - 소셜 로그인은 따로 필요없고, 이메일 기반 로그인만 회원가입 페이지 있음
(중요 : 지금 당장은 가장 중요한 소셜 로그인만 개발하고, 이메일 기반 회원가입/로그인은 나중에할것 - 12월말쯤 예상)
![Image](https://github.com/ASAC-marketplace/front/assets/5765169/ef39f5fb-ab81-48a2-9566-150fa306e1e3)

## ESTIMATE
**1.5d**

## TASKS
- [x] 회원가입 - 소셜
- [ ] 회원가입 - 이메일 1) 개인정보 및 연락처 인증
- [ ] 회원가입 - 이메일 2) 추가정보 (성별, 선호)
- [ ] 값 검증에 따른 알림 모달
