### ISSUE TITLE
[Refactor]Filter 리팩토링

### ISSUE THREAD

**Issue by yunjiisy** [ASAC-marketplace/frontend#141]
## ISSUE
- filter 컴포넌트 기능추가 및 리팩토링

## ESTIMATE
1.5d
## TASKS
- [ ] 필터 적용시 필터 버튼 색상 변경
- [ ] 카테고리 인터페이스 as const를 사용하여 리팩토링
- [ ] filterbottomsheet 컴포넌트 createPortal or Modal을 사용하여 리팩토링
- [ ] 필터 옵션 카테코리, 검색 이름 말고 id로 대체
- [ ] 정렬기능
